/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransitRouteImport } from './routes/transit'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MapRouteImport } from './routes/map'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'

const TransitRoute = TransitRouteImport.update({
  id: '/transit',
  path: '/transit',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/explore': typeof ExploreRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/spaces': typeof SpacesRoute
  '/transit': typeof TransitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/explore': typeof ExploreRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/spaces': typeof SpacesRoute
  '/transit': typeof TransitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/explore': typeof ExploreRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/spaces': typeof SpacesRoute
  '/transit': typeof TransitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/explore'
    | '/insights'
    | '/map'
    | '/profile'
    | '/spaces'
    | '/transit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/explore'
    | '/insights'
    | '/map'
    | '/profile'
    | '/spaces'
    | '/transit'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/explore'
    | '/insights'
    | '/map'
    | '/profile'
    | '/spaces'
    | '/transit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  ExploreRoute: typeof ExploreRoute
  InsightsRoute: typeof InsightsRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  SpacesRoute: typeof SpacesRoute
  TransitRoute: typeof TransitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transit': {
      id: '/transit'
      path: '/transit'
      fullPath: '/transit'
      preLoaderRoute: typeof TransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  ExploreRoute: ExploreRoute,
  InsightsRoute: InsightsRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  SpacesRoute: SpacesRoute,
  TransitRoute: TransitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
